### ISSUE TITLE
Input data

### ISSUE THREAD

**Issue by santiontanon** [MahsaDerakhshan/AffinityClustering#1]
Hi, I am trying to give this code a try, but there is no explanation anywhere about the format of the input data. How should I format my graph to be given as input?

**Comment by MahsaDerakhshan** [comment]
Input should contain the edges and their weights as tuples. It is assumed that vertices are labeled with integer numbers. Here is an example with four vertices and three edges.
1, 2 , 0.57
2, 3, 0.8
1, 4, 1.2

Note that, similar to what we have in the [paper](http://papers.nips.cc/paper/7262-affinity-clustering-hierarchical-clustering-at-scale-supplemental.zip), the input graph does not need to be complete.

**Comment by santiontanon** [comment]
Awesome, thanks a lot!
